---
  - name: Installing ambari-server
    yum: name=ambari-server state=latest

  - name: Ensure ambari-server is stopped
    service: name=ambari-server state=stopped

  - name: Configuring ambari-server
    shell: "ambari-server setup -j /usr/java/jdk1.8.0_131 -s > /tmp/ambari-install-output executable=/bin/bash"


  - name : Check if ambari-server is installed
    wait_for : path=/tmp/ambari-install-output search_regex="completed successfully"
   
  - name: Increase the Ambari Server startup timeout
    lineinfile:
     path: /etc/ambari-server/conf/ambari.properties
     state: present
     line: 'server.startup.web.timeout=120'
    notify: Restart ambari-server
   
  - name : Ensure ambari server started and enabled at reboot
    service : name=ambari-server state=started enabled=yes

  - name: Make sure the ambari-server service is enabled
    service:
     name: ambari-server
     enabled: yes
    ignore_errors: true

  - name: Copying mysql-connector jar
    copy:
     src: /tmp/resource/mysql-connector-java.jar
     dest: /tmp/resource/mysql-connector-java.jar

  - name: Configuring mysql-connector jar
    shell: "ambari-server setup --jdbc-db=mysql --jdbc-driver=/tmp/resource/mysql-connector-java.jar"
